server:
  port: 9641
spring:
  cloud:
    config:
      profile: dev
      uri: http://localhost:8871

  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 10.118.65.56:9300
#      repositories:
#        enabled: true
  jackson:
    date-format: java.text.SimpleDateFormat
#  jpa:
#    database: MYSQL
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    open-in-view: true
#    generate-ddl: true
#    database-platform:
#  datasource:
#    platform: MYSQL
#    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
#    username: root
#    password: Root
#    driver-class-name: com.mysql.cj.jdbc.Driver