spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
       ddl-auto: update
       generate-ddl: true
  datasource:
    platform: MYSQL
    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: Root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: resource-service-A
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: admin
      password: admin
security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://localhost:9991/oauth/token
      user-authorization-uri: http://localhost:9991/oauth/authorize
    resource:
      token-info-uri: http://localhost:9991/user
server:
  port: 9999
logging:
  level:
    org:
      springframework.security: DEBUG