spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 100ms
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
  datasource:
    dbcp2:
      validation-query: select 1 from DUAL