spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 100
  jpa:
    database: mysql
    show-sql: true
    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
  datasource:
    dbcp2:
      validation-query: select 1 from DUAL

        #    hibernate:
        #      ddl-auto: update
        #    generate-ddl: true
    platform: MYSQL
    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: Root
    driver-class-name: com.mysql.cj.jdbc.Driver
  zipkin:
    base-url: http://localhost:9411