
spring:
  application:
    name: security-service-A

  main:
    allow-bean-definition-overriding: true
#eureka:
#  client:
#    service-url:
#      defaultZone:
#        http://localhost:8761/eureka/
logging:
  level:
    org:
      springframework.web: DEBUG
