#spring:
#  jpa:
#    database: mysql
#    show-sql: true
#    database-platform: "mysql"
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#server:
#  port: 9999
#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations:
##          classpath:config/,classpath:config/db-service-dev
#            D:\workspace\IntelliJ Idea\springcloud\cloud-config\base-config\src\main\resources\config
#   Cannot determine local hostname: 由于本地有两个ip 所以当前系统不知道本地是哪个ip


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



server:
  port: 8888

#  基于git的配置
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MrEric125/springcloud
          search-paths: config
          username: 627460581@qq.com
          password: wzc5254tay...

