server:
  port: 7888
spring:
  application:
    name: producer
#  datasource:
#    platform: MYSQL
#    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
#    username: root
#    password: Root
#    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    stream:
      kafka:
        binder:
          #Kafka的消息中间件服务器
          brokers: localhost:9092
          #Zookeeper的节点，如果集群，后面加,号分隔
          zk-nodes: localhost:2181
          #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
          auto-create-topics: true
      bindings:
        #这里用stream给我们提供的默认output，后面会讲到自定义output
        output:
          #消息发往的目的地
          destination: stream-demo
          #消息发送的格式，接收端不用指定格式，但是发送端要
          content-type: text/plain
        louis_output:
          destination: stream-demo-demo
          content-type: text/plain