eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 60
spring:
  profiles:
    active: dev

logging:
  level:
    org.springframework: DEBUG
#    com: DEBUG