

server:
  port: 9751

spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
    generate-ddl: true
    database-platform:
  datasource:
      platform: MYSQL
      url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password: Root
      driver-class-name: com.mysql.cj.jdbc.Driver
#    The bean 'louis-order-web.FeignClientSpecification', defined in null, could not be registered.


  cloud:
    config:
      profile: dev
      uri: http://localhost:8871
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
  #    appname: louis-order-web
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/



