order:
  length: 25

server:
  port: 9751

spring:
  application:
    name: louis-order-web

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
    generate-ddl: true
    database-platform:
  datasource:
    platform: MYSQL
    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: Root
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
#指定在feign中的callback生效，一般在服务调用方需要指定，服务提供方可以不配置
feign:
  hystrix:
    enabled: true



